import 'foodModel.dart';

const FOOD_CATEGORIE = const [
  Categorie(
    id: 'c1',
    titre: 'Foutou',
  ),
  Categorie(
    id: 'c2',
    titre: 'Riz',
  ),
  Categorie(
    id: 'c3',
    titre: 'Attieké',
  ),
  Categorie(
    id: 'c4',
    titre: 'Sauces',
  ),
  Categorie(
    id: 'c5',
    titre: 'Poulet',
  ),
  Categorie(
    id: 'c6',
    titre: 'Alloco',
  ),
];

const PLATS_LISTS = [
  ModelPlats(
    id: 'p1',
    categories: ['c5'],
    titre: 'Veggie',
    sousTitre: 'tomato mix',
    price: '2000',
    image: 'images/food.png',
  ),
  ModelPlats(
    id: 'p2',
    categories: ['c5'],
    titre: 'Veggie',
    sousTitre: 'tomato remix',
    price: '1500',
    image: 'images/food1.png',
  ),
  ModelPlats(
    id: 'p3',
    categories: ['c1'],
    titre: 'Foufou',
    sousTitre: 'Bon foufou',
    price: '2000',
    image: 'images/foufou.jpg',
  ),
  ModelPlats(
    id: 'p4',
    categories: ['c1'],
    titre: 'Foutou',
    sousTitre: 'Foutou Banane ',
    price: '1500',
    image: 'images/foutou.jpg',
  ),
  ModelPlats(
    id: 'p5',
    categories: ['c1'],
    titre: 'Foutou',
    sousTitre: 'foutou Igname',
    price: '2000',
    image: 'images/foutou1.jpg',
  ),
  ModelPlats(
    id: 'p6',
    categories: ['c1'],
    titre: 'foutou',
    sousTitre: 'foutou manioc',
    price: '1500',
    image: 'images/foutou.jpg',
  ),
  ModelPlats(
    id: 'p7',
    categories: ['c3'],
    titre: 'Gaba',
    sousTitre: 'Gaba choco',
    price: '1500',
    image: 'images/gaba.jpg',
  ),
  ModelPlats(
    id: 'p8',
    categories: ['c3'],
    titre: 'Gaba',
    sousTitre: 'Pour tous',
    price: '1500',
    image: 'images/gaba1.jpg',
  ),
  ModelPlats(
    id: 'p9',
    categories: ['c3'],
    titre: 'Gaba',
    sousTitre: "Abidjan y'a les merveille",
    price: '1500',
    image: 'images/gaba2.jpg',
  ),
  ModelPlats(
    id: 'p10',
    categories: ['c2'],
    titre: 'riz',
    sousTitre: "riz gra",
    price: '1500',
    image: 'images/rizGra.jpg',
  ),
  ModelPlats(
    id: 'p11',
    categories: ['c2'],
    titre: 'Tchep',
    sousTitre: "Tche Senegalais",
    price: '1500',
    image: 'images/rizGra1.jpg',
  ),
  ModelPlats(
    id: 'p12',
    categories: ['c2'],
    titre: 'riz',
    sousTitre: "riz blanc",
    price: '1500',
    image: 'images/riz.jpg',
  ),
  ModelPlats(
    id: 'p13',
    categories: ['c6'],
    titre: 'Aloco',
    sousTitre: "Aloco piment",
    price: '3500',
    image: 'images/aloco.jpg',
  ),
  ModelPlats(
    id: 'p14',
    categories: ['c6'],
    titre: 'riz',
    sousTitre: "Aloco chaud",
    price: '1500',
    image: 'images/aloco1.jpg',
  ),
  ModelPlats(
    id: 'p15',
    categories: ['c6'],
    titre: 'Aloco',
    sousTitre: "Aloco pur",
    price: '1500',
    image: 'images/aloco2.jpg',
  ),
  ModelPlats(
    id: 'p16',
    categories: ['c6'],
    titre: 'Claclo',
    sousTitre: "Claclo chaud",
    price: '1500',
    image: 'images/claclo.jpg',
  ),
  ModelPlats(
    id: 'p17',
    categories: ['c4'],
    titre: 'Sauce',
    sousTitre: "Sauce feuille",
    price: '2000',
    image: 'images/saca.jpg',
  ),
  ModelPlats(
    id: 'p18',
    categories: ['c4'],
    titre: 'Sauce',
    sousTitre: "Sauce feuille",
    price: '2000',
    image: 'images/sauces.jpg',
  ),
];
