import 'package:flutter/cupertino.dart';

import 'foodModel.dart';

final FOOD_CATEGORIE = const [
  Categorie(
    id: 'c7',
    titre: 'Traditionelle',
  ),
  Categorie(
    id: 'c1',
    titre: 'foutou',
  ),
  Categorie(
    id: 'c2',
    titre: 'riz',
  ),
  Categorie(
    id: 'c3',
    titre: 'Attieké',
  ),
  Categorie(
    id: 'c4',
    titre: 'Sauces',
  ),
  Categorie(
    id: 'c5',
    titre: 'Poulet',
  ),
  Categorie(
    id: 'c6',
    titre: 'aloco',
  ),
];

List<ModelPlats> listDePLats = [
  ModelPlats(
    id: 'p32',
    idCategorie: 'c7',
    titre: 'Bawan',
    sousTitre: 'Feulle de manioc avec huil rouge ;-)',
    price: '400',
    image: 'images/foufou.jpg',
  ),
  ModelPlats(
    id: 'p4',
    idCategorie: 'c1',
    titre: 'Foutou',
    sousTitre: 'Foutou Banane ',
    price: '1500',
    image: 'images/foutou.jpg',
  ),
  ModelPlats(
    id: 'p5',
    idCategorie: 'c1',
    titre: 'Foutou',
    sousTitre: 'foutou Igname',
    price: '2000',
    image: 'images/foutou1.jpg',
  ),
  ModelPlats(
    id: 'p6',
    idCategorie: 'c1',
    titre: 'foutou',
    sousTitre: 'foutou manioc',
    price: '1500',
    image: 'images/foutou.jpg',
  ),
  ModelPlats(
    id: 'p3',
    idCategorie: 'c1',
    titre: 'Foufou',
    sousTitre: 'Bon foufou',
    price: '2000',
    image: 'images/foufou.jpg',
  ),
  ModelPlats(
    id: 'p4',
    idCategorie: 'c1',
    titre: 'Foutou',
    sousTitre: 'Foutou Banane ',
    price: '1500',
    image: 'images/foutou.jpg',
  ),
  ModelPlats(
    id: 'p5',
    idCategorie: 'c1',
    titre: 'Foutou',
    sousTitre: 'foutou Igname',
    price: '2000',
    image: 'images/foutou1.jpg',
  ),
  ModelPlats(
    id: 'p6',
    idCategorie: 'c1',
    titre: 'foutou',
    sousTitre: 'foutou manioc',
    price: '1500',
    image: 'images/foutou.jpg',
  ),
  ModelPlats(
    id: 'p10',
    idCategorie: 'c2',
    titre: 'riz',
    sousTitre: "riz gra",
    price: '1500',
    image: 'images/rizGra.jpg',
  ),
  ModelPlats(
    id: 'p11',
    idCategorie: 'c2',
    titre: 'Tchep',
    sousTitre: "Tche Senegalais",
    price: '1500',
    image: 'images/rizGra1.jpg',
  ),
  ModelPlats(
    id: 'p12',
    idCategorie: 'c2',
    titre: 'riz',
    sousTitre: "riz blanc",
    price: '1500',
    image: 'images/riz2.jpg',
  ),
  ModelPlats(
    id: 'p7',
    idCategorie: 'c3',
    titre: 'Gaba',
    sousTitre: 'Gaba choco',
    price: '1500',
    image: 'images/gaba.jpg',
  ),
  ModelPlats(
    id: 'p8',
    idCategorie: 'c3',
    titre: 'Gaba',
    sousTitre: 'Pour tous',
    price: '1500',
    image: 'images/gaba1.jpg',
  ),
  ModelPlats(
    id: 'p9',
    idCategorie: 'c3',
    titre: 'Gaba',
    sousTitre: "Abidjan y'a les merveille",
    price: '1500',
    image: 'images/gaba2.jpg',
  ),
  ModelPlats(
    id: 'p17',
    idCategorie: 'c4',
    titre: 'Sauce',
    sousTitre: "Sauce feuille",
    price: '2000',
    image: 'images/saca.jpg',
  ),
  ModelPlats(
    id: 'p18',
    idCategorie: 'c4',
    titre: 'Sauce',
    sousTitre: "Sauce feuille",
    price: '2000',
    image: 'images/sauces.jpg',
  ),
  ModelPlats(
    id: 'p1',
    idCategorie: 'c5',
    titre: 'Veggie',
    sousTitre: 'tomato mix',
    price: '2000',
    image: 'images/food.png',
  ),
  ModelPlats(
    id: 'p2',
    idCategorie: 'c5',
    titre: 'Veggie',
    sousTitre: 'tomato remix',
    price: '1500',
    image: 'images/food1.png',
  ),
  ModelPlats(
    id: 'p13',
    idCategorie: 'c6',
    titre: 'Aloco',
    sousTitre: "Aloco piment",
    price: '3500',
    image: 'images/aloco.jpg',
  ),
  ModelPlats(
    id: 'p14',
    idCategorie: 'c6',
    titre: 'riz',
    sousTitre: "Aloco chaud",
    price: '1500',
    image: 'images/aloco1.jpg',
  ),
  ModelPlats(
    id: 'p15',
    idCategorie: 'c6',
    titre: 'Aloco',
    sousTitre: "Aloco pur",
    price: '1500',
    image: 'images/aloco2.jpg',
  ),
  ModelPlats(
    id: 'p16',
    idCategorie: 'c6',
    titre: 'Claclo',
    sousTitre: "Claclo chaud",
    price: '1500',
    image: 'images/claclo.jpg',
  ),
];
